# Generated by Django 3.2.6 on 2021-08-28 14:43

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('Objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
